package com.hallth.domain;

public class MytyUserSubjectScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_user_subject_score.agenda_round_no
     *
     * @mbggenerated
     */
    private Integer agendaRoundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_user_subject_score.dm_id
     *
     * @mbggenerated
     */
    private Integer dmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_user_subject_score.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_user_subject_score.user_comment
     *
     * @mbggenerated
     */
    private String userComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_user_subject_score.user_judge
     *
     * @mbggenerated
     */
    private Integer userJudge;

    private Integer subjectRank;

    public Integer getSubjectRank() {
        return subjectRank;
    }

    public void setSubjectRank(Integer subjectRank) {
        this.subjectRank = subjectRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_user_subject_score.agenda_round_no
     *
     * @return the value of myty_user_subject_score.agenda_round_no
     *
     * @mbggenerated
     */
    public Integer getAgendaRoundNo() {
        return agendaRoundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_user_subject_score.agenda_round_no
     *
     * @param agendaRoundNo the value for myty_user_subject_score.agenda_round_no
     *
     * @mbggenerated
     */
    public void setAgendaRoundNo(Integer agendaRoundNo) {
        this.agendaRoundNo = agendaRoundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_user_subject_score.dm_id
     *
     * @return the value of myty_user_subject_score.dm_id
     *
     * @mbggenerated
     */
    public Integer getDmId() {
        return dmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_user_subject_score.dm_id
     *
     * @param dmId the value for myty_user_subject_score.dm_id
     *
     * @mbggenerated
     */
    public void setDmId(Integer dmId) {
        this.dmId = dmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_user_subject_score.user_id
     *
     * @return the value of myty_user_subject_score.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_user_subject_score.user_id
     *
     * @param userId the value for myty_user_subject_score.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_user_subject_score.user_comment
     *
     * @return the value of myty_user_subject_score.user_comment
     *
     * @mbggenerated
     */
    public String getUserComment() {
        return userComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_user_subject_score.user_comment
     *
     * @param userComment the value for myty_user_subject_score.user_comment
     *
     * @mbggenerated
     */
    public void setUserComment(String userComment) {
        this.userComment = userComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_user_subject_score.user_judge
     *
     * @return the value of myty_user_subject_score.user_judge
     *
     * @mbggenerated
     */
    public Integer getUserJudge() {
        return userJudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_user_subject_score.user_judge
     *
     * @param userJudge the value for myty_user_subject_score.user_judge
     *
     * @mbggenerated
     */
    public void setUserJudge(Integer userJudge) {
        this.userJudge = userJudge;
    }
}