package com.hallth.domain;

import lombok.Data;

@Data
public class SysDictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.KEY
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.VALUE
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.DEL_FLAG
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.IS_AVAILABLE
     *
     * @mbggenerated
     */
    private String isAvailable;
    private String isAvailableCn;

    private int startRow;
    private int pageSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.ID
     *
     * @return the value of sys_dictionary.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.ID
     *
     * @param id the value for sys_dictionary.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.TYPE
     *
     * @return the value of sys_dictionary.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.TYPE
     *
     * @param type the value for sys_dictionary.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.DESCRIPTION
     *
     * @return the value of sys_dictionary.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.DESCRIPTION
     *
     * @param description the value for sys_dictionary.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.KEY
     *
     * @return the value of sys_dictionary.KEY
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.KEY
     *
     * @param key the value for sys_dictionary.KEY
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.VALUE
     *
     * @return the value of sys_dictionary.VALUE
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.VALUE
     *
     * @param value the value for sys_dictionary.VALUE
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.REMARKS
     *
     * @return the value of sys_dictionary.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.REMARKS
     *
     * @param remarks the value for sys_dictionary.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.DEL_FLAG
     *
     * @return the value of sys_dictionary.DEL_FLAG
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.DEL_FLAG
     *
     * @param delFlag the value for sys_dictionary.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.IS_AVAILABLE
     *
     * @return the value of sys_dictionary.IS_AVAILABLE
     *
     * @mbggenerated
     */
    public String getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.IS_AVAILABLE
     *
     * @param isAvailable the value for sys_dictionary.IS_AVAILABLE
     *
     * @mbggenerated
     */
    public void setIsAvailable(String isAvailable) {
        this.isAvailable = isAvailable;
    }
}