package com.hallth.domain;

import lombok.Data;

@Data
public class SystemInfo {
    private int startRow;
    private int pageSize;
    private String isAvailableCn;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.SYS_ID
     *
     * @mbggenerated
     */
    private String sysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.SYS_NAME
     *
     * @mbggenerated
     */
    private String sysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.HOME_ADDRESS
     *
     * @mbggenerated
     */
    private String homeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.SYS_ABBREVIATIONS
     *
     * @mbggenerated
     */
    private String sysAbbreviations;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.SYS_ICON
     *
     * @mbggenerated
     */
    private String sysIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.IS_AVAILABLE
     *
     * @mbggenerated
     */
    private String isAvailable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.ID
     *
     * @return the value of system_info.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.ID
     *
     * @param id the value for system_info.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.SYS_ID
     *
     * @return the value of system_info.SYS_ID
     *
     * @mbggenerated
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.SYS_ID
     *
     * @param sysId the value for system_info.SYS_ID
     *
     * @mbggenerated
     */
    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.SYS_NAME
     *
     * @return the value of system_info.SYS_NAME
     *
     * @mbggenerated
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.SYS_NAME
     *
     * @param sysName the value for system_info.SYS_NAME
     *
     * @mbggenerated
     */
    public void setSysName(String sysName) {
        this.sysName = sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.HOME_ADDRESS
     *
     * @return the value of system_info.HOME_ADDRESS
     *
     * @mbggenerated
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.HOME_ADDRESS
     *
     * @param homeAddress the value for system_info.HOME_ADDRESS
     *
     * @mbggenerated
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.SYS_ABBREVIATIONS
     *
     * @return the value of system_info.SYS_ABBREVIATIONS
     *
     * @mbggenerated
     */
    public String getSysAbbreviations() {
        return sysAbbreviations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.SYS_ABBREVIATIONS
     *
     * @param sysAbbreviations the value for system_info.SYS_ABBREVIATIONS
     *
     * @mbggenerated
     */
    public void setSysAbbreviations(String sysAbbreviations) {
        this.sysAbbreviations = sysAbbreviations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.SYS_ICON
     *
     * @return the value of system_info.SYS_ICON
     *
     * @mbggenerated
     */
    public String getSysIcon() {
        return sysIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.SYS_ICON
     *
     * @param sysIcon the value for system_info.SYS_ICON
     *
     * @mbggenerated
     */
    public void setSysIcon(String sysIcon) {
        this.sysIcon = sysIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.IS_AVAILABLE
     *
     * @return the value of system_info.IS_AVAILABLE
     *
     * @mbggenerated
     */
    public String getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.IS_AVAILABLE
     *
     * @param isAvailable the value for system_info.IS_AVAILABLE
     *
     * @mbggenerated
     */
    public void setIsAvailable(String isAvailable) {
        this.isAvailable = isAvailable;
    }
}