package com.hallth.domain;

import lombok.Data;

@Data
public class TargetInfo {
    private int startRow;
    private int pageSize;
    private String nullalbeCn;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_info.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_info.EN_NAME
     *
     * @mbggenerated
     */
    private String enName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_info.CN_NAME
     *
     * @mbggenerated
     */
    private String cnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_info.DATA_TYPE
     *
     * @mbggenerated
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_info.LENGTH
     *
     * @mbggenerated
     */
    private Integer length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_info.NULLALBE
     *
     * @mbggenerated
     */
    private String nullalbe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_info.IS_PK
     *
     * @mbggenerated
     */
    private String isPk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_info.DEFAULT_VALUE
     *
     * @mbggenerated
     */
    private String defaultValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_info.ID
     *
     * @return the value of target_info.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_info.ID
     *
     * @param id the value for target_info.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_info.EN_NAME
     *
     * @return the value of target_info.EN_NAME
     *
     * @mbggenerated
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_info.EN_NAME
     *
     * @param enName the value for target_info.EN_NAME
     *
     * @mbggenerated
     */
    public void setEnName(String enName) {
        this.enName = enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_info.CN_NAME
     *
     * @return the value of target_info.CN_NAME
     *
     * @mbggenerated
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_info.CN_NAME
     *
     * @param cnName the value for target_info.CN_NAME
     *
     * @mbggenerated
     */
    public void setCnName(String cnName) {
        this.cnName = cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_info.DATA_TYPE
     *
     * @return the value of target_info.DATA_TYPE
     *
     * @mbggenerated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_info.DATA_TYPE
     *
     * @param dataType the value for target_info.DATA_TYPE
     *
     * @mbggenerated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_info.LENGTH
     *
     * @return the value of target_info.LENGTH
     *
     * @mbggenerated
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_info.LENGTH
     *
     * @param length the value for target_info.LENGTH
     *
     * @mbggenerated
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_info.NULLALBE
     *
     * @return the value of target_info.NULLALBE
     *
     * @mbggenerated
     */
    public String getNullalbe() {
        return nullalbe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_info.NULLALBE
     *
     * @param nullalbe the value for target_info.NULLALBE
     *
     * @mbggenerated
     */
    public void setNullalbe(String nullalbe) {
        this.nullalbe = nullalbe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_info.IS_PK
     *
     * @return the value of target_info.IS_PK
     *
     * @mbggenerated
     */
    public String getIsPk() {
        return isPk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_info.IS_PK
     *
     * @param isPk the value for target_info.IS_PK
     *
     * @mbggenerated
     */
    public void setIsPk(String isPk) {
        this.isPk = isPk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_info.DEFAULT_VALUE
     *
     * @return the value of target_info.DEFAULT_VALUE
     *
     * @mbggenerated
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_info.DEFAULT_VALUE
     *
     * @param defaultValue the value for target_info.DEFAULT_VALUE
     *
     * @mbggenerated
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }
}