package com.hallth.domain;

public class TbCuUserOpenBsec {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.BOSS_CITY_CODE
     *
     * @mbggenerated
     */
    private String bossCityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.CITY_NAME
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.CNTY_TYPE
     *
     * @mbggenerated
     */
    private String cntyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.CNTY_NAME
     *
     * @mbggenerated
     */
    private String cntyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.GROUP_CONTCT_TEL
     *
     * @mbggenerated
     */
    private String groupContctTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.CUST_CONTCS_SERV_NO
     *
     * @mbggenerated
     */
    private String custContcsServNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.SERV_CODE
     *
     * @mbggenerated
     */
    private String servCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.STAFF_EPLYID
     *
     * @mbggenerated
     */
    private String staffEplyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.GC_CODE
     *
     * @mbggenerated
     */
    private String gcCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.GROUP_NAME
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.IS_HEART_SHOP
     *
     * @mbggenerated
     */
    private String isHeartShop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.MNGR_MNGR_SERV_NO
     *
     * @mbggenerated
     */
    private String mngrMngrServNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.SHOP_TYPE
     *
     * @mbggenerated
     */
    private String shopType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.ADDR_NAME
     *
     * @mbggenerated
     */
    private String addrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.CAMPN_PKG_DESC_1
     *
     * @mbggenerated
     */
    private String campnPkgDesc1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.CAMP_DISC_CODE
     *
     * @mbggenerated
     */
    private String campDiscCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.CAMP_DISC_NAME
     *
     * @mbggenerated
     */
    private String campDiscName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.OPR_TYPE
     *
     * @mbggenerated
     */
    private String oprType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.OPER_TIME
     *
     * @mbggenerated
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.RSRV_STR_1
     *
     * @mbggenerated
     */
    private String rsrvStr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.RSRV_STR_2
     *
     * @mbggenerated
     */
    private String rsrvStr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cu_user_open_bsec.RSRV_STR_3
     *
     * @mbggenerated
     */
    private String rsrvStr3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.BOSS_CITY_CODE
     *
     * @return the value of tb_cu_user_open_bsec.BOSS_CITY_CODE
     *
     * @mbggenerated
     */
    public String getBossCityCode() {
        return bossCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.BOSS_CITY_CODE
     *
     * @param bossCityCode the value for tb_cu_user_open_bsec.BOSS_CITY_CODE
     *
     * @mbggenerated
     */
    public void setBossCityCode(String bossCityCode) {
        this.bossCityCode = bossCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.CITY_NAME
     *
     * @return the value of tb_cu_user_open_bsec.CITY_NAME
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.CITY_NAME
     *
     * @param cityName the value for tb_cu_user_open_bsec.CITY_NAME
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.CNTY_TYPE
     *
     * @return the value of tb_cu_user_open_bsec.CNTY_TYPE
     *
     * @mbggenerated
     */
    public String getCntyType() {
        return cntyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.CNTY_TYPE
     *
     * @param cntyType the value for tb_cu_user_open_bsec.CNTY_TYPE
     *
     * @mbggenerated
     */
    public void setCntyType(String cntyType) {
        this.cntyType = cntyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.CNTY_NAME
     *
     * @return the value of tb_cu_user_open_bsec.CNTY_NAME
     *
     * @mbggenerated
     */
    public String getCntyName() {
        return cntyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.CNTY_NAME
     *
     * @param cntyName the value for tb_cu_user_open_bsec.CNTY_NAME
     *
     * @mbggenerated
     */
    public void setCntyName(String cntyName) {
        this.cntyName = cntyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.GROUP_CONTCT_TEL
     *
     * @return the value of tb_cu_user_open_bsec.GROUP_CONTCT_TEL
     *
     * @mbggenerated
     */
    public String getGroupContctTel() {
        return groupContctTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.GROUP_CONTCT_TEL
     *
     * @param groupContctTel the value for tb_cu_user_open_bsec.GROUP_CONTCT_TEL
     *
     * @mbggenerated
     */
    public void setGroupContctTel(String groupContctTel) {
        this.groupContctTel = groupContctTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.CUST_CONTCS_SERV_NO
     *
     * @return the value of tb_cu_user_open_bsec.CUST_CONTCS_SERV_NO
     *
     * @mbggenerated
     */
    public String getCustContcsServNo() {
        return custContcsServNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.CUST_CONTCS_SERV_NO
     *
     * @param custContcsServNo the value for tb_cu_user_open_bsec.CUST_CONTCS_SERV_NO
     *
     * @mbggenerated
     */
    public void setCustContcsServNo(String custContcsServNo) {
        this.custContcsServNo = custContcsServNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.SERV_CODE
     *
     * @return the value of tb_cu_user_open_bsec.SERV_CODE
     *
     * @mbggenerated
     */
    public String getServCode() {
        return servCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.SERV_CODE
     *
     * @param servCode the value for tb_cu_user_open_bsec.SERV_CODE
     *
     * @mbggenerated
     */
    public void setServCode(String servCode) {
        this.servCode = servCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.STAFF_EPLYID
     *
     * @return the value of tb_cu_user_open_bsec.STAFF_EPLYID
     *
     * @mbggenerated
     */
    public String getStaffEplyid() {
        return staffEplyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.STAFF_EPLYID
     *
     * @param staffEplyid the value for tb_cu_user_open_bsec.STAFF_EPLYID
     *
     * @mbggenerated
     */
    public void setStaffEplyid(String staffEplyid) {
        this.staffEplyid = staffEplyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.GC_CODE
     *
     * @return the value of tb_cu_user_open_bsec.GC_CODE
     *
     * @mbggenerated
     */
    public String getGcCode() {
        return gcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.GC_CODE
     *
     * @param gcCode the value for tb_cu_user_open_bsec.GC_CODE
     *
     * @mbggenerated
     */
    public void setGcCode(String gcCode) {
        this.gcCode = gcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.GROUP_NAME
     *
     * @return the value of tb_cu_user_open_bsec.GROUP_NAME
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.GROUP_NAME
     *
     * @param groupName the value for tb_cu_user_open_bsec.GROUP_NAME
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.IS_HEART_SHOP
     *
     * @return the value of tb_cu_user_open_bsec.IS_HEART_SHOP
     *
     * @mbggenerated
     */
    public String getIsHeartShop() {
        return isHeartShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.IS_HEART_SHOP
     *
     * @param isHeartShop the value for tb_cu_user_open_bsec.IS_HEART_SHOP
     *
     * @mbggenerated
     */
    public void setIsHeartShop(String isHeartShop) {
        this.isHeartShop = isHeartShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.MNGR_MNGR_SERV_NO
     *
     * @return the value of tb_cu_user_open_bsec.MNGR_MNGR_SERV_NO
     *
     * @mbggenerated
     */
    public String getMngrMngrServNo() {
        return mngrMngrServNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.MNGR_MNGR_SERV_NO
     *
     * @param mngrMngrServNo the value for tb_cu_user_open_bsec.MNGR_MNGR_SERV_NO
     *
     * @mbggenerated
     */
    public void setMngrMngrServNo(String mngrMngrServNo) {
        this.mngrMngrServNo = mngrMngrServNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.SHOP_TYPE
     *
     * @return the value of tb_cu_user_open_bsec.SHOP_TYPE
     *
     * @mbggenerated
     */
    public String getShopType() {
        return shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.SHOP_TYPE
     *
     * @param shopType the value for tb_cu_user_open_bsec.SHOP_TYPE
     *
     * @mbggenerated
     */
    public void setShopType(String shopType) {
        this.shopType = shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.ADDR_NAME
     *
     * @return the value of tb_cu_user_open_bsec.ADDR_NAME
     *
     * @mbggenerated
     */
    public String getAddrName() {
        return addrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.ADDR_NAME
     *
     * @param addrName the value for tb_cu_user_open_bsec.ADDR_NAME
     *
     * @mbggenerated
     */
    public void setAddrName(String addrName) {
        this.addrName = addrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.CAMPN_PKG_DESC_1
     *
     * @return the value of tb_cu_user_open_bsec.CAMPN_PKG_DESC_1
     *
     * @mbggenerated
     */
    public String getCampnPkgDesc1() {
        return campnPkgDesc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.CAMPN_PKG_DESC_1
     *
     * @param campnPkgDesc1 the value for tb_cu_user_open_bsec.CAMPN_PKG_DESC_1
     *
     * @mbggenerated
     */
    public void setCampnPkgDesc1(String campnPkgDesc1) {
        this.campnPkgDesc1 = campnPkgDesc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.CAMP_DISC_CODE
     *
     * @return the value of tb_cu_user_open_bsec.CAMP_DISC_CODE
     *
     * @mbggenerated
     */
    public String getCampDiscCode() {
        return campDiscCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.CAMP_DISC_CODE
     *
     * @param campDiscCode the value for tb_cu_user_open_bsec.CAMP_DISC_CODE
     *
     * @mbggenerated
     */
    public void setCampDiscCode(String campDiscCode) {
        this.campDiscCode = campDiscCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.CAMP_DISC_NAME
     *
     * @return the value of tb_cu_user_open_bsec.CAMP_DISC_NAME
     *
     * @mbggenerated
     */
    public String getCampDiscName() {
        return campDiscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.CAMP_DISC_NAME
     *
     * @param campDiscName the value for tb_cu_user_open_bsec.CAMP_DISC_NAME
     *
     * @mbggenerated
     */
    public void setCampDiscName(String campDiscName) {
        this.campDiscName = campDiscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.OPR_TYPE
     *
     * @return the value of tb_cu_user_open_bsec.OPR_TYPE
     *
     * @mbggenerated
     */
    public String getOprType() {
        return oprType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.OPR_TYPE
     *
     * @param oprType the value for tb_cu_user_open_bsec.OPR_TYPE
     *
     * @mbggenerated
     */
    public void setOprType(String oprType) {
        this.oprType = oprType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.OPER_TIME
     *
     * @return the value of tb_cu_user_open_bsec.OPER_TIME
     *
     * @mbggenerated
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.OPER_TIME
     *
     * @param operTime the value for tb_cu_user_open_bsec.OPER_TIME
     *
     * @mbggenerated
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.RSRV_STR_1
     *
     * @return the value of tb_cu_user_open_bsec.RSRV_STR_1
     *
     * @mbggenerated
     */
    public String getRsrvStr1() {
        return rsrvStr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.RSRV_STR_1
     *
     * @param rsrvStr1 the value for tb_cu_user_open_bsec.RSRV_STR_1
     *
     * @mbggenerated
     */
    public void setRsrvStr1(String rsrvStr1) {
        this.rsrvStr1 = rsrvStr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.RSRV_STR_2
     *
     * @return the value of tb_cu_user_open_bsec.RSRV_STR_2
     *
     * @mbggenerated
     */
    public String getRsrvStr2() {
        return rsrvStr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.RSRV_STR_2
     *
     * @param rsrvStr2 the value for tb_cu_user_open_bsec.RSRV_STR_2
     *
     * @mbggenerated
     */
    public void setRsrvStr2(String rsrvStr2) {
        this.rsrvStr2 = rsrvStr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cu_user_open_bsec.RSRV_STR_3
     *
     * @return the value of tb_cu_user_open_bsec.RSRV_STR_3
     *
     * @mbggenerated
     */
    public String getRsrvStr3() {
        return rsrvStr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cu_user_open_bsec.RSRV_STR_3
     *
     * @param rsrvStr3 the value for tb_cu_user_open_bsec.RSRV_STR_3
     *
     * @mbggenerated
     */
    public void setRsrvStr3(String rsrvStr3) {
        this.rsrvStr3 = rsrvStr3;
    }
}