package com.hallth.domain;

import java.util.Date;

public class UserSystemRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_system_rel.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_system_rel.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_system_rel.SYS_ID
     *
     * @mbggenerated
     */
    private Integer sysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_system_rel.START_TIME
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_system_rel.END_TIME
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_system_rel.ID
     *
     * @return the value of user_system_rel.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_system_rel.ID
     *
     * @param id the value for user_system_rel.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_system_rel.USER_ID
     *
     * @return the value of user_system_rel.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_system_rel.USER_ID
     *
     * @param userId the value for user_system_rel.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_system_rel.SYS_ID
     *
     * @return the value of user_system_rel.SYS_ID
     *
     * @mbggenerated
     */
    public Integer getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_system_rel.SYS_ID
     *
     * @param sysId the value for user_system_rel.SYS_ID
     *
     * @mbggenerated
     */
    public void setSysId(Integer sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_system_rel.START_TIME
     *
     * @return the value of user_system_rel.START_TIME
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_system_rel.START_TIME
     *
     * @param startTime the value for user_system_rel.START_TIME
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_system_rel.END_TIME
     *
     * @return the value of user_system_rel.END_TIME
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_system_rel.END_TIME
     *
     * @param endTime the value for user_system_rel.END_TIME
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}