package com.hallth.mapper;

import com.hallth.domain.TbCuUserOpenBsec;

public interface TbCuUserOpenBsecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cu_user_open_bsec
     *
     * @mbggenerated
     */
    int insert(TbCuUserOpenBsec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cu_user_open_bsec
     *
     * @mbggenerated
     */
    int insertSelective(TbCuUserOpenBsec record);
}