package com.hallth.mapper;

import com.hallth.domain.SystemInfo;
import com.hallth.domain.User;
import com.hallth.domain.UserSystemRel;

import java.util.List;

public interface UserSystemRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_system_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_system_rel
     *
     * @mbggenerated
     */
    int insert(UserSystemRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_system_rel
     *
     * @mbggenerated
     */
    int insertSelective(UserSystemRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_system_rel
     *
     * @mbggenerated
     */
    UserSystemRel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_system_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserSystemRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_system_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserSystemRel record);

    /**
     * 查询用户有权限的系统列表
     * */
    List<SystemInfo> queryAvailalbeSystemList(User user);
}